### PR TITLE
Feature chams

### PR DESCRIPTION
**Pull request by maecry**

### CODE REVIEW

**Comment by maecry** [comment]
will merge after cleaning up code and stuffs? idk

**Comment by fL1pSt3r** [comment]
I think it's possible to get an entity instead of getting an object type number.
In CMaterialData: CSceneAnimatableObject* at 0x10
In CSceneAnimatableObject: CSkeletonInstance* at 0xF8
in CSkeletonInstance inheritance from CGameSceneNode - m_pOwner (CEntityInstance*)
and already from СEntityInstance get the required entity
credits: https://www.unknowncheats.me/forum/3899273-post7.html

**Comment by maecry** [comment]
> I think it's possible to get an entity instead of getting an object type number. In CMaterialData: CSceneAnimatableObject* at 0x10 In CSceneAnimatableObject: CSkeletonInstance* at 0xF8 in CSkeletonInstance inheritance from CGameSceneNode - m_pOwner (CEntityInstance*) and already from СEntityInstance get the required entity credits: https://www.unknowncheats.me/forum/3899273-post7.html

thanks for the in4

**Comment by fL1pSt3r** [comment]
Some misinformation, apologies
CSceneAnimatableObject at 0xF8 isn't a pointer to CSkeletonInstance
image
CSceneObject refers to CBodyComponentBaseAnimGraph, which holds CSkeletonInstance at 0x50 and owner entity at 0x80
(0x30 relative to CSkeletonInstance)
So, u just need to minus 0x120 (or don't hardcode it) from CSceneAnimatable offset and grab pointer to entity

**Comment by maecry** [comment]
thanks again, i get your idea + after looking thru https://github.com/neverlosecc/source2sdk/tree/cs2/sdk, i will figure out this later when i have the time as rn im kidna busy irl, really appreciate your help

**Comment by dankor33** [comment]
If someone wants the armor bar put it in menu.cpp where healthOverlayConfig is
		if (const auto& armorOverlayConfig = C_GET(BarOverlayVar_t, Vars.overlayArmorBar); armorOverlayConfig.bEnable)
		{
			const float armorFactor = M_SIN(ImGui::GetTime() * 5.f) * 0.55f + 0.45f;
			context.AddComponent(new CBarComponent(true, SIDE_BOTTOM, vecBox, armorFactor, Vars.overlayArmorBar));
		}

**Comment by maecry** [comment]
> If someone wants the armor bar put it in menu.cpp where healthOverlayConfig is if (const auto& armorOverlayConfig = C_GET(BarOverlayVar_t, Vars.overlayArmorBar); armorOverlayConfig.bEnable) { const float armorFactor = M_SIN(ImGui::GetTime() * 5.f) * 0.55f + 0.45f; context.AddComponent(new CBarComponent(true, SIDE_BOTTOM, vecBox, armorFactor, Vars.overlayArmorBar)); }
> 
> this is kinda broken when I have time do config thing I will post the fix later

make a pr tho the base itself should be easy to add that (if u have 1 active brain cell)+ the thing you sent is only on the preview for the menu

**Comment by maecry** [comment]
broken invisible chams but idc rn

**Pull request merged**
